config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments, only: [:create]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title, :body
    belongs_to :user
    has_one_attached :cover_picture
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts,    dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    @comment = Post.find(params[:post_id]).comments.new(comment_params)
    @comment.assign_attributes(user_id: current_user.id)

    if !@comment.save
      flash[:notice] = @comment.errors.full_messages.to_sentence
    end
    redirect_to post_path(params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [ :edit, :update, :destroy]

  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      flash[:notice] = @post.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    if @post.user_id == current_user&.id
      @post.destroy
      redirect_to posts_path
    end
  end



private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:cover_picture, :title, :summary, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<article>
  <p><%= comment.content %></p>
  <small>от <%= comment.user.email %></small>
</article>

<hr /> 

app/views/comments/_form.html.erb
<form action="<%= post_comments_path(post) %>" method="post">
  <input name="authenticity_token" type="hidden">

  <textarea name="comment[content]" rows="5" cols="20"></textarea>

  <input type="submit" value="Опубликовать комменатрий">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= link_to 'Все статьи', posts_path%>
    <%= link_to 'Новая статья', new_post_path %>
  
<ul class="navbar-nav mr-auto">
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= button_to 'Выход', destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to 'Вход', new_user_session_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Регистрация', new_user_registration_path, class: "nav-link" %>
    </li>
  <% end %>
</ul>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class='form-group'>
    <%= f.label :cover_picture %>
    <%= f.file_field :cover_picture %>
  </div>

  <div class="form-control">
    <%= f.label :title%>
    <%= f.text_area :title%>
  </div>

   <div class="form-control">
    <%= f.label :summary %>
    <%= f.text_area :summary %>
  </div>

   <div class="form-control">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

   <div class="form-control">
    <%= f.submit 'Сохранить'%>
  </div>
<% end %> 

app/views/posts/edit.html.erb
<h1>Редактирование поста</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Посты</h1>
<% @post.each do |post| %>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <section>
    <%= image_tag post.cover_picture, width: "40%" if post.cover_picture.attached? %>
   <p>Краткое описание: <%= post.summary %></p>
</section>
<% end %>

app/views/posts/new.html.erb
<h2>Новая статья</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<% if @post.cover_picture.attached? %>
    <%= image_tag @post.cover_picture, width: "40%" %>
<% end %>



<h2>Краткое описание</h2>
<p> <%= @post.summary %> </p>


<strong>Текст поста</strong>
<p><%= @post.body %> </p>
<section>
<small>Опубликован: <% if @post.user.email == current_user&.email %></small>
  опубликован вами
  <% else %>
  <%= @post.user.email %>
  <% end %>
  <small>
    <%if @post.user_id == current_user&.id %>
      <%= link_to 'Редактировать пост', edit_post_path(@post) %>
      <%= link_to 'Удалить пост',post_path(@post), method: :delete, data: {confirm: 'Вы уверены?'} %>
    <% end %> 
  </section>
  <p>
    <strong>Комментарии:</strong>
    <%= render @post.comments %>
    <%= render partial: 'comments/form', locals: { post: @post } %>
  </p>